Refs #32339 -- Fixed super() call in deprecated renderers.
Missing function call `()` leads to:

TypeError: descriptor '__init__' of 'super' object needs an argument

Regression in 8591cc08060abf2b853ffd40a6b414d93f0a84ef.